### ISSUE TITLE
Is the `GL/glu.h` file included by any CDT package?

### ISSUE THREAD

**Issue by capn-freako** [conda-forge/cdt-builds#64]
### Comment:

Even with all entries suggested [here](https://conda-forge.org/docs/maintainer/knowledge_base.html#libgl) included in my build recipe:

```yaml
requirements:
  build:
    - {{ compiler('c')   }}
    - {{ compiler('cxx') }}
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('mesa-dri1-drivers') }}      # [linux]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - cmake
    - git
    - swig
  host:
    {snip}
```

I'm getting:

```
  In file included from kiva/gl/gl_wrap.cpp:3671:
  kiva/gl/src/kiva_gl_graphics_context.h:25:14: fatal error: GL/glu.h: No such file or directory
     25 |     #include <GL/glu.h>
        |              ^~~~~~~~~~
  compilation terminated.
```

And I'm wondering: does _any_ CDT package provide the `GL/glu.h` file?

Is the following sufficient to claim that no CDT package includes the `glu.h` file?
Asked differently, is every file that is included in, at least, one CDT package mentioned somewhere within the `conda-forge/cdt-builds` repo.?

```
$ git clone https://github.com/conda-forge/cdt-builds.git
Cloning into 'cdt-builds'...
{snip}

$ pushd cdt-builds/

$ git grep 'glu\.h'

$
```

Oh, I think I just answered my own question.  
I _know_ that the `mesa-libgl-devel` package provides the `GL/gl.h` file, but...

```
% git grep 'gl.h'
{no output}
```

**So, then, how does one figure out whether a particular file is provided by a CDT package?**

Thanks!
-db
